name: github_webview_app
description: A Flutter app that opens a GitHub page in WebView and handles links in default browser.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.2.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  url_launcher: ^6.1.10
  android_intent_plus: ^6.0.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
